# Generated by Django 4.0.4 on 2022-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')])),
            ],
        ),
        migrations.CreateModel(
            name='Cardss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, verbose_name='Карточка')),
                ('num', models.IntegerField(verbose_name='Номер_колонки')),
                ('column_choices', models.IntegerField(choices=[('ON', 'One'), ('TW', 'Two'), ('TH', 'Three')], default='ON')),
            ],
        ),
    ]
