# Generated by Django 4.0.4 on 2022-05-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cards_cardss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elemet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250, verbose_name='Карточка')),
                ('num', models.IntegerField(verbose_name='Номер_колонки')),
            ],
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
