# Generated by Django 4.0.4 on 2022-05-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_elemet_delete_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elemet',
            name='num',
            field=models.IntegerField(default=1, verbose_name='Номер_колонки'),
        ),
    ]
